sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
python:
  - "3.4"
services:
  - postgresql
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=dev
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - psql -c 'create database test;' -U postgres
  - cd models
  - node sync.js
  - cd ..
before_install:
  - cd data
  - python3 -V
  - python3 -c "import sys;print('\n'.join(sys.path))"
  - sudo apt-get -y install python3-pip
  - pip3 install bs4
  - pip3 install lxml
  - pip3 list
  - pip3 show lxml
  - cd ..
install:
  - cd backend
  - npm install
script:
  - npm test
  - cd ..
  - cd data
  - python3 -m unittest test/test_moviedata.py
